language: node_js
node_js:
    - "7.4.0"

addons:
    chrome: stable

sudo: false

cache:
    directories:
        - node_modules

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn --prefer-offline --pure-lockfile
    - ./node_modules/bower/bin/bower install --config.interactive=false

    - npm config set spin false
    - npm install -g bower
    - bower --version
    - npm install phantomjs-prebuilt
    - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
    - yarn install
    - bower install
script:
    - yarn test
after_success:
    - ember github-pages:commit --message "gh-pages release"
    - 'HELLdO'
