install:
    - cp -r ./client/* ./
    - cp -r ./client/.* ./
    - yarn install
    - bower install
script:
    - ember github-pages:commit --message "gh-pages release"
after_success:
    - 'HELLdO'
